name: Deno:CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check-all:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "latest"

      - name: Run formatting check
        run: deno fmt --check

      - name: Run lint check
        run: deno lint

      - name: Run type check
        run: deno check

      - name: Run tests
        run: deno test
