name: Deno:publish

on:
  push:
    tags:
      - "v*"

jobs:
  check-all:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run formatting check
        run: deno fmt --check

      - name: Run lint check
        run: deno lint

      - name: Run type check
        run: deno check

      - name: Run tests
        run: deno test

  publish:
    runs-on: ubuntu-latest
    needs: check-all

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
