name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: make

      - name: Run fmt check
        run: make fmt-check

      - name: Run type check
        run: make type-check

      - name: Run tests
        run: make test

      - name: Run build lib
        run: make build

      - name: Run build docs
        run: make docs-build

      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure Git for documentation deployment
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy documentation website
        run: make docs-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
